// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnRN6UTefZ01D73N1U5zEIkL_Zga0C8OE',
    appId: '1:591603607687:web:02dd5d5bf637968fcf3022',
    messagingSenderId: '591603607687',
    projectId: 'geowell',
    authDomain: 'geowell.firebaseapp.com',
    storageBucket: 'geowell.appspot.com',
    measurementId: 'G-8YX5XNEH8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUN03u2kt_W3mdVsRTjdGLBcm2XFpkCiE',
    appId: '1:591603607687:android:22b5f667af75150ecf3022',
    messagingSenderId: '591603607687',
    projectId: 'geowell',
    storageBucket: 'geowell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd4sWc3YFc20JtUDh_E9SPMiQbQ7_yNcI',
    appId: '1:591603607687:ios:4815129d4c7046a8cf3022',
    messagingSenderId: '591603607687',
    projectId: 'geowell',
    storageBucket: 'geowell.appspot.com',
    androidClientId: '591603607687-lfrgdtmpj86f62henrfb23q2cqjrtsvr.apps.googleusercontent.com',
    iosClientId: '591603607687-nmukt6d3fn3jot3qb1upk2l921q1rrnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd4sWc3YFc20JtUDh_E9SPMiQbQ7_yNcI',
    appId: '1:591603607687:ios:cb139f886cfafb67cf3022',
    messagingSenderId: '591603607687',
    projectId: 'geowell',
    storageBucket: 'geowell.appspot.com',
    androidClientId: '591603607687-lfrgdtmpj86f62henrfb23q2cqjrtsvr.apps.googleusercontent.com',
    iosClientId: '591603607687-f8d2cj8farviue41buif333j81s3mcdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocery.RunnerTests',
  );
}
